# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Depending on OS
if [[ $(uname -o) == "Android" ]]; then
  if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zaliases_android" ]]; then
    source "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zaliases_android"
  fi
else
  if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zaliases" ]]; then
    source "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zaliases"
  fi

  if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zaliases_arco" ]]; then
    source "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zaliases_arco"
  fi

  # Search backwards and forwards with a pattern
  bindkey -M vicmd '^[R' history-incremental-pattern-search-backward
  bindkey -M vicmd '^[F' history-incremental-pattern-search-forward
  # Set up for insert mode too
  bindkey -M viins '^[R' history-incremental-pattern-search-backward
  bindkey -M viins '^[F' history-incremental-pattern-search-forward

  ## Workaround for handling TERM variable in multiple tmux sessions properly -
  # Source:
  # https://wiki.archlinux.org/index.php/tmux#Correct_the_TERM_variable_according_to_terminal_type

  if [[ -n ${TMUX} && -n ${commands[tmux]} ]]; then
    case $(tmux showenv TERM 2>/dev/null) in
      *256color) ;&
      TERM=fbterm)
        TERM=screen-256color ;;
      *)
        TERM=screen
    esac
  fi
fi


# dotglob lets glob match dotfiles
setopt dotglob

# allow overwritting existing files
#setopt CLOBBER     # Use '>!' and '>>!' when this is commented out.

# Disabled: CDABLE_VARS changes directory to a path stored in a variable.
setopt nocdablevars


# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
